packages:
  - apps/*
  - packages/*

catalogMode: prefer
catalog:
  "@effect/platform-node": 4.0.0-rc.112
  "@better-auth/oauth-provider": 1.7.3
  better-auth: 1.7.3
  effect: 4.0.0-rc.112
  "@types/node": 26.5.0
  jose: 6.2.12
  typescript: 7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.3.1
  vite-plus: 0.3.1
  playwright: 1.62.1
  "@effect/sql-sqlite-node": 4.0.0-rc.112
  kysely: 0.29.5
  "@better-auth/core": 1.7.3

overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
allowBuilds:
  msgpackr-extract: false
minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.3.1"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.3.1"
  - "@voidzero-dev/vite-plus-darwin-x64@0.3.1"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.3.1"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.3.1"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.3.1"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.3.1"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.3.1"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.3.1"
  - vite-plus@0.3.1
patchedDependencies:
  "@better-auth/oauth-provider@1.7.3": patches/@better-auth__oauth-provider@1.7.3.patch
